# Stubs for pandas.core.missing (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

def mask_missing(arr: Any, values_to_mask: Any): ...
def clean_fill_method(method: Any, allow_nearest: bool = ...): ...
def clean_interp_method(method: Any, **kwargs: Any): ...
def interpolate_1d(
    xvalues: Any,
    yvalues: Any,
    method: str = ...,
    limit: Optional[Any] = ...,
    limit_direction: str = ...,
    limit_area: Optional[Any] = ...,
    fill_value: Optional[Any] = ...,
    bounds_error: bool = ...,
    order: Optional[Any] = ...,
    **kwargs: Any
): ...
def interpolate_2d(
    values: Any,
    method: str = ...,
    axis: int = ...,
    limit: Optional[Any] = ...,
    fill_value: Optional[Any] = ...,
    dtype: Optional[Any] = ...,
): ...
def pad_1d(
    values: Any,
    limit: Optional[Any] = ...,
    mask: Optional[Any] = ...,
    dtype: Optional[Any] = ...,
): ...
def backfill_1d(
    values: Any,
    limit: Optional[Any] = ...,
    mask: Optional[Any] = ...,
    dtype: Optional[Any] = ...,
): ...
def pad_2d(
    values: Any,
    limit: Optional[Any] = ...,
    mask: Optional[Any] = ...,
    dtype: Optional[Any] = ...,
): ...
def backfill_2d(
    values: Any,
    limit: Optional[Any] = ...,
    mask: Optional[Any] = ...,
    dtype: Optional[Any] = ...,
): ...
def get_fill_func(method: Any): ...
def clean_reindex_fill_method(method: Any): ...
def fill_zeros(result: Any, x: Any, y: Any, name: Any, fill: Any): ...
def mask_zero_div_zero(x: Any, y: Any, result: Any, copy: bool = ...): ...
def dispatch_missing(op: Any, left: Any, right: Any, result: Any): ...
