# Stubs for pandas.core.dtypes.concat (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def get_dtype_kinds(l: Any): ...
def union_categoricals(
    to_union: Any, sort_categories: bool = ..., ignore_order: bool = ...
): ...
