# Stubs for pandas.core.dtypes.missing (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .common import _NS_DTYPE, _TD_DTYPE, ensure_object, is_bool_dtype, is_complex_dtype, is_datetime64_dtype, is_datetime64tz_dtype, is_datetimelike, is_datetimelike_v_numeric, is_dtype_equal, is_extension_array_dtype, is_float_dtype, is_integer_dtype, is_object_dtype, is_period_dtype, is_scalar, is_string_dtype, is_string_like_dtype, is_timedelta64_dtype, needs_i8_conversion, pandas_dtype
from .generic import ABCDatetimeArray, ABCExtensionArray, ABCGeneric, ABCIndexClass, ABCMultiIndex, ABCSeries, ABCTimedeltaArray
from .inference import is_list_like
from typing import Any

isposinf_scalar: Any
isneginf_scalar: Any

def isna(obj: Any): ...
isnull = isna

def notna(obj: Any): ...
notnull = notna

def array_equivalent(left: Any, right: Any, strict_nan: bool = ...): ...
def na_value_for_dtype(dtype: Any, compat: bool = ...): ...
def remove_na_arraylike(arr: Any): ...
