# Stubs for pandas.core.arrays._ranges (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def generate_regular_range(start: Any, end: Any, periods: Any, freq: Any): ...
