# Stubs for pandas.core.arrays.array_ (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Optional

def array(
    data: Sequence[object],
    dtype: Optional[Union[str, np.dtype, ExtensionDtype]] = ...,
    copy: bool = ...,
) -> ExtensionArray: ...
