# Stubs for pandas.core.groupby.base (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

class GroupByMixin: ...

plotting_methods: Any
common_apply_whitelist: Any
series_apply_whitelist: Any
dataframe_apply_whitelist: Any
cython_transforms: Any
cython_cast_blacklist: Any

def whitelist_method_generator(base: Any, klass: Any, whitelist: Any) -> None: ...
