# Stubs for pandas.core.groupby.categorical (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def recode_for_groupby(c: Any, sort: Any, observed: Any): ...
def recode_from_groupby(c: Any, sort: Any, ci: Any): ...
