# Stubs for pandas.util._exceptions (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def rewrite_exception(old_name: Any, new_name: Any) -> None: ...
