# Stubs for pandas.util._tester (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

def test(extra_args: Optional[Any] = ...) -> None: ...
