# Stubs for pandas.util._test_decorators (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

def safe_import(mod_name: Any, min_version: Optional[Any] = ...): ...
def skip_if_no(package: Any, min_version: Optional[Any] = ...): ...

skip_if_no_mpl: Any
skip_if_np_lt_115: Any
skip_if_mpl: Any
xfail_if_mpl_2_2: Any
skip_if_32bit: Any
skip_if_windows: Any
skip_if_windows_python_3: Any
skip_if_has_locale: Any
skip_if_not_us_locale: Any
skip_if_no_scipy: Any
skip_if_no_lzma: Any
skip_if_no_ne: Any

def parametrize_fixture_doc(*args: Any): ...
