# Stubs for pandas.core.tools.numeric (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

def to_numeric(arg: Any, errors: str = ..., downcast: Optional[Any] = ...): ...
