# Stubs for pandas.core.tools.timedeltas (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def to_timedelta(arg: Any, unit: str = ..., box: bool = ..., errors: str = ...): ...
