# Stubs for pandas.core.internals (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .blocks import (
    Block,
    BoolBlock,
    CategoricalBlock,
    ComplexBlock,
    DatetimeBlock,
    DatetimeTZBlock,
    ExtensionBlock,
    FloatBlock,
    IntBlock,
    ObjectBlock,
    TimeDeltaBlock,
    _block2d_to_blocknd,
    _block_shape,
    _factor_indexer,
    _safe_reshape,
    make_block,
)
from .managers import (
    BlockManager,
    SingleBlockManager,
    concatenate_block_managers,
    create_block_manager_from_arrays,
    create_block_manager_from_blocks,
    items_overlap_with_suffix,
)
