# Stubs for pandas.plotting._tools (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

def format_date_labels(ax: Any, rot: Any) -> None: ...
def table(
    ax: Any,
    data: Any,
    rowLabels: Optional[Any] = ...,
    colLabels: Optional[Any] = ...,
    **kwargs: Any
): ...
